name: tk_iot
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  mqtt_client: ^10.11.11
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  window_manager: ^0.5.1
  mobile_scanner: ^7.2.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png