// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcc0nNZ5zCOSgy8ROrDVaPQlI6gRHuu00',
    appId: '1:107089443410:web:fc83649eb017eeb0e9fd8b',
    messagingSenderId: '107089443410',
    projectId: 'smart-home-1743843741242',
    authDomain: 'smart-home-1743843741242.firebaseapp.com',
    storageBucket: 'smart-home-1743843741242.firebasestorage.app',
    measurementId: 'G-4KTSQJML40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpVwkq-5vFf3hxkGneIjWF3LXjm5QR2U',
    appId: '1:107089443410:android:7b729dcab8904334e9fd8b',
    messagingSenderId: '107089443410',
    projectId: 'smart-home-1743843741242',
    storageBucket: 'smart-home-1743843741242.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxjeh4Ed_PVPIPosufSR-TS2DyelQeGo',
    appId: '1:107089443410:ios:777e98fd34834376e9fd8b',
    messagingSenderId: '107089443410',
    projectId: 'smart-home-1743843741242',
    storageBucket: 'smart-home-1743843741242.firebasestorage.app',
    iosBundleId: 'com.example.tkIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqxjeh4Ed_PVPIPosufSR-TS2DyelQeGo',
    appId: '1:107089443410:ios:777e98fd34834376e9fd8b',
    messagingSenderId: '107089443410',
    projectId: 'smart-home-1743843741242',
    storageBucket: 'smart-home-1743843741242.firebasestorage.app',
    iosBundleId: 'com.example.tkIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcc0nNZ5zCOSgy8ROrDVaPQlI6gRHuu00',
    appId: '1:107089443410:web:1a22f5a3c10c63aae9fd8b',
    messagingSenderId: '107089443410',
    projectId: 'smart-home-1743843741242',
    authDomain: 'smart-home-1743843741242.firebaseapp.com',
    storageBucket: 'smart-home-1743843741242.firebasestorage.app',
    measurementId: 'G-XDFT2W0F8Z',
  );
}
